server.port=8085
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
spring.servlet.multipart.resolve-lazily=true

# ETERNA Configuration
eterna.api.base-url=http://localhost:8080
eterna.api.username=admin
eterna.api.password=eterna